[profile.default]
src = "src"
script = "scripts"
out = "out"
libs = ["lib"]
via_ir = false
optimizer = true
optimizer_runs = 100

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

fs_permissions = [
  { access='read', path='./configs' },
  { access='read', path='./test' },
  { access='write', path='./deployment.json' }
]
